name: package
on:
  push:
    branches:
    - main
    - test
jobs:
  package_snap:
    name: Create Snap
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: snapcore/action-build@v1
      id: snapcraft
    - uses: actions/upload-artifact@v2
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}
  package_web:
    name: Create Web Assembly
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: ./actions/build-web
    - uses: actions/upload-artifact@v2
      with:
        name: web
        path: bin
  package_win:
    name: Create Windows binary
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Configure
      shell: powershell
      run: cmake . -DCMAKE_BUILD_TYPE=Release
    - name: Build
      shell: powershell
      run: cmake --build . --config Release
    - uses: actions/upload-artifact@v2
      with:
        name: win
        path: bin
